<?php

mb_internal_encoding('UTF-8');
mb_http_output('UTF-8');


include "back/classes/loggin.php";
include "back/classes/lang.php";

$LangGalery = new Language("lang/", "loggin");

$conn = new Conexion("back/conexion.json");

$conn->SessionChequed("loggin");

?>

<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="es">
 <head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <meta name="generator" content="openElement (1.57.9)" />
  
  <meta name="viewport" content="width=420px, initial-scale=1" />
  <link id="openElement" rel="stylesheet" type="text/css" href="admin//openElement.css?v=50491112400" />
  <link id="OEBase" rel="stylesheet" type="text/css" href="loggin.css?v=50491112400" />
  <!--[if lte IE 7]>
  <link rel="stylesheet" type="text/css" href="WEFiles/Css/ie7.css?v=50491112400" />
  <![endif]-->
  <script type="text/javascript">
   var WEInfoPage = {"PHPVersion":"phpOK","OEVersion":"1-57-9","PagePath":"loggin","Culture":"DEFAULT","LanguageCode":"ES","RelativePath":"","RenderMode":"Export","PageAssociatePath":"loggin","EditorTexts":null};
  </script>
  <script type="text/javascript" src="plugins/1.10.2.js?v=50491112400"></script>
  <script type="text/javascript" src="plugins/oe.min.js?v=50491112400"></script>
  

  <script type="text/javascript" src="js/classes/lang.js">
    
  </script>

  <style id="OEScriptManager" type="text/css">
   .wobble-hor-top{-webkit-animation:wobble-hor-top .8s both;animation:wobble-hor-top .8s both}
   
   /* ----------------------------------------------
    * Generated by Animista on 2020-7-19 14:21:27
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */
   
   @-webkit-keyframes wobble-hor-top{0%,100%{-webkit-transform:translateX(0);transform:translateX(0);-webkit-transform-origin:50% 50%;transform-origin:50% 50%}15%{-webkit-transform:translateX(-30px) rotate(6deg);transform:translateX(-30px) rotate(6deg)}30%{-webkit-transform:translateX(15px) rotate(-6deg);transform:translateX(15px) rotate(-6deg)}45%{-webkit-transform:translateX(-15px) rotate(3.6deg);transform:translateX(-15px) rotate(3.6deg)}60%{-webkit-transform:translateX(9px) rotate(-2.4deg);transform:translateX(9px) rotate(-2.4deg)}75%{-webkit-transform:translateX(-6px) rotate(1.2deg);transform:translateX(-6px) rotate(1.2deg)}}@keyframes wobble-hor-top{0%,100%{-webkit-transform:translateX(0);transform:translateX(0);-webkit-transform-origin:50% 50%;transform-origin:50% 50%}15%{-webkit-transform:translateX(-30px) rotate(6deg);transform:translateX(-30px) rotate(6deg)}30%{-webkit-transform:translateX(15px) rotate(-6deg);transform:translateX(15px) rotate(-6deg)}45%{-webkit-transform:translateX(-15px) rotate(3.6deg);transform:translateX(-15px) rotate(3.6deg)}60%{-webkit-transform:translateX(9px) rotate(-2.4deg);transform:translateX(9px) rotate(-2.4deg)}75%{-webkit-transform:translateX(-6px) rotate(1.2deg);transform:translateX(-6px) rotate(1.2deg)}}
  </style>
  
  
  <?php


	
$listargrupos = false;
$err = false;


//$SQL_Partida_CHEK = "SELECT id, nombre, lang FROM dinamic_partidas WHERE fecha_inicio < NOW() AND fecha_fin > NOW() AND Estado = 1 LIMIT 1";
$SQL_Partida_CHEK = "SELECT id, nombre, lang FROM dinamic_partidas WHERE date(fecha_inicio) < NOW() AND date(fecha_fin) > (NOW() - INTERVAL 1 DAY) AND Estado = 1 LIMIT 1";
  $checkpartida = mysqli_query($conn->conn(), $SQL_Partida_CHEK);
  $EstadoPartida = mysqli_num_rows($checkpartida);
  $lang = "-es";
 
  if ($checkpartida && $EstadoPartida >= 1){
    $partida_activa = mysqli_fetch_assoc($checkpartida);
    $titulopartida = " - ".$partida_activa["nombre"];
    $listargrupos = true;
    $idPartidaActiva = $partida_activa["id"];
    $lang = "-".$partida_activa["lang"];
  }
  echo "<title>Roadmap Game ".$titulopartida."</title>";



// Dibujar grupos Activos:

               if ($listargrupos){

               $SQLEQ = "SELECT Din.id AS id, Din.id_grupo AS id_grupo, Sta.Nombre AS Nombre, Din.total_Jugadores AS total_Jugadores FROM dinamic_grupos AS Din
               INNER JOIN static_grupos AS Sta
                 WHERE Din.id_grupo = Sta.id
                 AND Din.id_partida = ".$idPartidaActiva."
                 ";

               $equiposactivos = mysqli_query($conn->conn(), $SQLEQ);

               if ($equiposactivos){
				   
				   echo '<script type="text/javascript">Disp = [';
				

                  while ($grups=mysqli_fetch_Assoc($equiposactivos)){
                    echo '{grupo: '.($grups["id_grupo"]+1).', players: '.$grups["total_Jugadores"].', titulo:"'.$grups["Nombre"].'"},';
                  }
				  
          echo '	   ];</script>';

               }

              } else {
                echo '<script type="text/javascript">Disp = [];</script>';
              }



  ?>

  <script type="text/javascript">

  function err(){
   	var p = document.getElementById("WEc753fb2dba");
   	p.style.visibility = "visible";
   	
   	setTimeout(() => {
   		p.style.visibility = "hidden";
   	}, 2500);
   	
   }

   GaleryServ = <?= $LangGalery->getLanguageJson() ?>;
   ThisLang = new LangControl(GaleryServ);
   
   lang_op = "<?= $lang ?>";
   lang_bnd = [{o:"-es", b:"WE549b6b4c6b", 
    id: ThisLang.GetLabel("es", 2) /*"Idioma"*/, 
    gr: ThisLang.GetLabel("es", 0) /* "Grupo" */, 
    btn: ThisLang.GetLabel("es", 3) /*"Ingresar"*/, 
    err: ThisLang.GetLabel("es", 4) /*"Clave Incorrecta"*/, 
    Pass: ThisLang.GetLabel("es", 1) /*"Contraseña"*/},
    
    {o:"-en", b:"WE160e673c1f", 
      id: ThisLang.GetLabel("en", 2) /*"Language"*/, 
      gr: ThisLang.GetLabel("en", 0), 
      btn: ThisLang.GetLabel("en", 3), 
      err: ThisLang.GetLabel("en", 4), 
      Pass: ThisLang.GetLabel("en", 1)},

     {o:"-pr", b:"WE526c044191", 
      id: ThisLang.GetLabel("pr", 2) /*"Língua"*/, 
      gr:ThisLang.GetLabel("pr", 0), 
      btn:ThisLang.GetLabel("pr", 3), 
      err:ThisLang.GetLabel("pr", 4), 
      Pass:ThisLang.GetLabel("pr", 1)}]

    

    
function lang(e){
	
	lang_bnd.forEach((s)=>{
		if (s.o != e){
		document.getElementById(s.b).style.opacity = "0.4";
		} else {
			document.getElementById(s.b).style.opacity = "1.0";
		}
		
	});
	
	lang_op = e;
	
	label_Grupo = document.getElementById('WE90fab36798').children[0].children[0];
	label_Pass = document.getElementById('WE9f2b86dcbc').children[0].children[0];
	label_btn = document.getElementById('WE66637a0e2c').children[0].children[0];
	label_idiom = document.getElementById('WEb675f77523').children[0].children[0];
	label_err = document.getElementById('WE866637ab59').children[0].children[0];
	
	
	opc = lang_bnd.find((s)=>{return s.o == e});
	
	label_Grupo.innerText = opc.gr;
	label_Pass.innerText = opc.Pass;
	label_btn.innerText = opc.btn;
	label_idiom.innerText = opc.id;
	label_err.innerText = opc.err;
	
}
   
   
  </script>
  <link rel="preload" as="image" href="Images/logo-WE71cb131790.png">
  <link rel="preload" as="image" href="Images/default_user-WE6ba5a1362d.png">
  <style>
  	input:focus, textarea:focus, select:focus{
          outline: none;
      }
  </style><?php
  	if (isset($oeHeaderInlineCode)) echo $oeHeaderInlineCode;
  ?>
 </head>
 <body class="RWAuto" data-gl="{&quot;KeywordsHomeNotInherits&quot;:false}"><?php
  	if (isset($oeStartBodyInlineCode)) echo $oeStartBodyInlineCode;
  ?>
  <form id="XForm" method="post" action="#"></form>
  <div id="XBody" class="BaseDiv RBoth OEPageXbody OESK_XBody_Default" style="z-index:0">
   <div class="OESZ OESZ_DivContent OESZG_XBody">
    <div class="OESZ OESZ_XBodyContent OESZG_XBody OECT OECT_Content OECTAbs">
     <div id="WEed2d2cd9b1" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OECenterAV" style="z-index:1">
      <div class="OESZ OESZ_DivContent OESZG_WEed2d2cd9b1">
       <div class="OECT OECT_Content OECTAbs OEDynTag0">
        <div id="WE9517b0e2cf" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default OECenterAH wobble-hor-top" style="z-index:1">
         <div class="OESZ OESZ_DivContent OESZG_WE9517b0e2cf">
          <img src="Images/logo-WE9517b0e2cf.png" class="OESZ OESZ_Img OESZG_WE9517b0e2cf" alt="" />
         </div>
        </div>
        <div id="WE1b57b02841" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OECenterAH" style="z-index:14">
         <div class="OESZ OESZ_DivContent OESZG_WE1b57b02841">
          <div class="OECT OECT_Content OECTRel OEDynTag0" style="overflow:auto">
           <div class="OERelLine OEHAlignC OEVAlignB">
            <div id="WE173386c7b3" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OEGo" style="z-index:1">
             <div class="OESZ OESZ_DivContent OESZG_WE173386c7b3">
              <a href="javascript:SelecGr(1)">
               <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:visible">
                <div id="WE8c90227353" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:1">
                 <div class="OESZ OESZ_DivContent OESZG_WE8c90227353">
                  <img src="Images/G1-WE8c90227353.png" class="OESZ OESZ_Img OESZG_WE8c90227353" alt="" />
                 </div>
                </div>
                <div id="WE464044606a" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:3">
                 <div class="OESZ OESZ_DivContent OESZG_WE464044606a">
                  <span class="OESZ OESZ_Text OESZG_WE464044606a ContentBox">10</span>
                 </div>
                </div>
                <div id="WE0c25bbd77c" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2">
                 <div class="OESZ OESZ_DivContent OESZG_WE0c25bbd77c">
                  <span class="OESZ OESZ_Text OESZG_WE0c25bbd77c ContentBox">Grupo 1</span>
                 </div>
                </div>
               </div>
              </a>
             </div>
            </div><div id="WE9127cfd672" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OEGo" style="z-index:2">
             <div class="OESZ OESZ_DivContent OESZG_WE9127cfd672">
              <a href="javascript:SelecGr(2)">
               <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:visible">
                <div id="WEb7e0f2bfe2" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:1">
                 <div class="OESZ OESZ_DivContent OESZG_WEb7e0f2bfe2">
                  <img src="Images/G_2-WEb7e0f2bfe2.png" class="OESZ OESZ_Img OESZG_WEb7e0f2bfe2" alt="" />
                 </div>
                </div>
                <div id="WE435e4e43ae" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:3">
                 <div class="OESZ OESZ_DivContent OESZG_WE435e4e43ae">
                  <span class="OESZ OESZ_Text OESZG_WE435e4e43ae ContentBox">10</span>
                 </div>
                </div>
                <div id="WE21909d36d1" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2">
                 <div class="OESZ OESZ_DivContent OESZG_WE21909d36d1">
                  <span class="OESZ OESZ_Text OESZG_WE21909d36d1 ContentBox">Grupo 2</span>
                 </div>
                </div>
               </div>
              </a>
             </div>
            </div><div id="WE14a13a312a" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OEGo" style="z-index:3">
             <div class="OESZ OESZ_DivContent OESZG_WE14a13a312a">
              <a href="javascript:SelecGr(3)">
               <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:visible">
                <div id="WE6a3fa0ca8e" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:1">
                 <div class="OESZ OESZ_DivContent OESZG_WE6a3fa0ca8e">
                  <img src="Images/G_3-WE6a3fa0ca8e.png" class="OESZ OESZ_Img OESZG_WE6a3fa0ca8e" alt="" />
                 </div>
                </div>
                <div id="WE839e99d445" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:3">
                 <div class="OESZ OESZ_DivContent OESZG_WE839e99d445">
                  <span class="OESZ OESZ_Text OESZG_WE839e99d445 ContentBox">10</span>
                 </div>
                </div>
                <div id="WE23ab4eb10c" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2">
                 <div class="OESZ OESZ_DivContent OESZG_WE23ab4eb10c">
                  <span class="OESZ OESZ_Text OESZG_WE23ab4eb10c ContentBox">Grupo 3</span>
                 </div>
                </div>
               </div>
              </a>
             </div>
            </div><div id="WEa3d5b41229" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OEGo" style="z-index:4">
             <div class="OESZ OESZ_DivContent OESZG_WEa3d5b41229">
              <a href="javascript:SelecGr(4)">
               <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:visible">
                <div id="WE25221949f7" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:1">
                 <div class="OESZ OESZ_DivContent OESZG_WE25221949f7">
                  <img src="Images/G_4-WE25221949f7.png" class="OESZ OESZ_Img OESZG_WE25221949f7" alt="" />
                 </div>
                </div>
                <div id="WE5802a483dc" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:3">
                 <div class="OESZ OESZ_DivContent OESZG_WE5802a483dc">
                  <span class="OESZ OESZ_Text OESZG_WE5802a483dc ContentBox">10</span>
                 </div>
                </div>
                <div id="WE026db0c144" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2">
                 <div class="OESZ OESZ_DivContent OESZG_WE026db0c144">
                  <span class="OESZ OESZ_Text OESZG_WE026db0c144 ContentBox">Grupo 4</span>
                 </div>
                </div>
               </div>
              </a>
             </div>
            </div><div id="WE7ee2fd68dd" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OEGo" style="z-index:5">
             <div class="OESZ OESZ_DivContent OESZG_WE7ee2fd68dd">
              <a href="javascript:SelecGr(5)">
               <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:visible">
                <div id="WE05144a68b7" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:1">
                 <div class="OESZ OESZ_DivContent OESZG_WE05144a68b7">
                  <img src="Images/G_5-WE05144a68b7.png" class="OESZ OESZ_Img OESZG_WE05144a68b7" alt="" />
                 </div>
                </div>
                <div id="WE1e15c6cc8f" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:3">
                 <div class="OESZ OESZ_DivContent OESZG_WE1e15c6cc8f">
                  <span class="OESZ OESZ_Text OESZG_WE1e15c6cc8f ContentBox">10</span>
                 </div>
                </div>
                <div id="WEd7132d1792" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2">
                 <div class="OESZ OESZ_DivContent OESZG_WEd7132d1792">
                  <span class="OESZ OESZ_Text OESZG_WEd7132d1792 ContentBox">Grupo 5</span>
                 </div>
                </div>
               </div>
              </a>
             </div>
            </div><div id="WE4e3be8ab56" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OEGo" style="z-index:6">
             <div class="OESZ OESZ_DivContent OESZG_WE4e3be8ab56">
              <a href="javascript:SelecGr(6)">
               <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:visible">
                <div id="WEa910e033a3" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:1">
                 <div class="OESZ OESZ_DivContent OESZG_WEa910e033a3">
                  <img src="Images/G_6-WEa910e033a3.png" class="OESZ OESZ_Img OESZG_WEa910e033a3" alt="" />
                 </div>
                </div>
                <div id="WE39ccac8113" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:3">
                 <div class="OESZ OESZ_DivContent OESZG_WE39ccac8113">
                  <span class="OESZ OESZ_Text OESZG_WE39ccac8113 ContentBox">10</span>
                 </div>
                </div>
                <div id="WE91b412e8fe" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2">
                 <div class="OESZ OESZ_DivContent OESZG_WE91b412e8fe">
                  <span class="OESZ OESZ_Text OESZG_WE91b412e8fe ContentBox">Grupo 6</span>
                 </div>
                </div>
               </div>
              </a>
             </div>
            </div><div id="WE73a8ae1cdf" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OEGo" style="z-index:7">
             <div class="OESZ OESZ_DivContent OESZG_WE73a8ae1cdf">
              <a href="javascript:SelecGr(7)">
               <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:visible">
                <div id="WE58d4d7752b" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:1">
                 <div class="OESZ OESZ_DivContent OESZG_WE58d4d7752b">
                  <img src="Images/G7-WE58d4d7752b.png" class="OESZ OESZ_Img OESZG_WE58d4d7752b" alt="" />
                 </div>
                </div>
                <div id="WE8ead86b8f2" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:3">
                 <div class="OESZ OESZ_DivContent OESZG_WE8ead86b8f2">
                  <span class="OESZ OESZ_Text OESZG_WE8ead86b8f2 ContentBox">10</span>
                 </div>
                </div>
                <div id="WEa3f8bf198d" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2">
                 <div class="OESZ OESZ_DivContent OESZG_WEa3f8bf198d">
                  <span class="OESZ OESZ_Text OESZG_WEa3f8bf198d ContentBox">Grupo 7</span>
                 </div>
                </div>
               </div>
              </a>
             </div>
            </div>
           </div>
          </div>
         </div>
        </div>
        <div id="WE90fab36798" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:6">
         <div class="OESZ OESZ_DivContent OESZG_WE90fab36798">
          <span class="OESZ OESZ_Text OESZG_WE90fab36798 ContentBox">Grupo:</span>
         </div>
        </div>
        <div id="WE6ba5a1362d" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:5">
         <div class="OESZ OESZ_DivContent OESZG_WE6ba5a1362d">
          <img src="Images/G_3-WE6ba5a1362d.png" class="OESZ OESZ_Img OESZG_WE6ba5a1362d" alt="" />
         </div>
        </div>
        <div id="WE4d4fa5f596" class="BaseDiv RHeight OEWEPanel OESK_WEPanel_Default" style="z-index:2">
         <div class="OESZ OESZ_DivContent OESZG_WE4d4fa5f596">
          <a href="javascript:SelecGr(0)">
           <div class="OECT OECT_Content OECTAbs OEDynTag0">
            <div id="WE1e073f9aea" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:1">
             <div class="OESZ OESZ_DivContent OESZG_WE1e073f9aea">
              <span class="OESZ OESZ_Text OESZG_WE1e073f9aea ContentBox">Admin</span>
             </div>
            </div>
            <div id="WE25aca0fd45" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2">
             <div class="OESZ OESZ_DivContent OESZG_WE25aca0fd45">
              <img src="Images/despleg-WE25aca0fd45.png" class="OESZ OESZ_Img OESZG_WE25aca0fd45" alt="" />
             </div>
            </div>
           </div>
          </a>
         </div>
        </div>
        <div id="WEc753fb2dba" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OECenterAH" style="z-index:9">
         <div class="OESZ OESZ_DivContent OESZG_WEc753fb2dba">
          <div class="OECT OECT_Content OECTAbs OEDynTag0">
           <div id="WE866637ab59" class="BaseDiv RBoth OEWELabel OESK_WELabel_Default OECenterAB" style="z-index:1">
            <div class="OESZ OESZ_DivContent OESZG_WE866637ab59">
             <span class="OESZ OESZ_Text OESZG_WE866637ab59 ContentBox">Clave Incorrecta</span>
            </div>
           </div>
          </div>
         </div>
        </div>
        <div id="WE8284213653" class="BaseDiv RBoth OEWECodeBlock OESK_WECodeBlock_Default OECenterAH" style="z-index:15">
         <div class="OESZ OESZ_DivContent OESZG_WE8284213653">
          <style>.lds-circle {
            display: inline-block;
          	
            transform: translateZ(1px);
          }
          .lds-circle > div {
          	
            display: inline-block;
            width: 64px;
            height: 64px;
            margin: 8px;
          	
            border-radius: 50%;
          	
            background: #fff;
            animation: lds-circle 2.4s cubic-bezier(0, 0.2, 0.8, 1) infinite;
          }
          @keyframes lds-circle {
            0%, 100% {
              animation-timing-function: cubic-bezier(0.5, 0, 1, 0.5);
            }
            0% {
              transform: rotateY(0deg);
            }
            50% {
              transform: rotateY(1800deg);
              animation-timing-function: cubic-bezier(0, 0.5, 0.5, 1);
            }
            100% {
              transform: rotateY(3600deg);
            }
          }
          </style>
          <div class="lds-circle" ><div style="background-image: url('Images/charg.jpg');background-size:cover;"></div></div>
         </div>
        </div>
        <div id="WE9f2b86dcbc" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:7">
         <div class="OESZ OESZ_DivContent OESZG_WE9f2b86dcbc">
          <span class="OESZ OESZ_Text OESZG_WE9f2b86dcbc ContentBox">Password</span>
         </div>
        </div>
        <div id="WE2916de4b64" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:8">
         <div class="OESZ OESZ_DivContent OESZG_WE2916de4b64">
          <img src="Images/default_user-WE2916de4b64.png" class="OESZ OESZ_Img OESZG_WE2916de4b64" alt="" />
         </div>
        </div>
        <div id="WE66eeb536ab" class="BaseDiv RHeight OEWEPanel OESK_WEPanel_Default" style="z-index:3">
         <div class="OESZ OESZ_DivContent OESZG_WE66eeb536ab">
          <div class="OECT OECT_Content OECTAbs OEDynTag0">
           <div id="WE177a810db7" class="BaseDiv RNone OEWETextBoxV2 OESK_WETextBox2_Default" style="z-index:1">
            <div class="OESZ OESZ_DivContent OESZG_WE177a810db7">
             <input name="Pass" type="password" class="OESZ OESZ_TextBox OESZG_WE177a810db7 OEd OEDynTag0" />
            </div>
           </div>
          </div>
         </div>
        </div>
        <div id="WEb675f77523" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:13">
         <div class="OESZ OESZ_DivContent OESZG_WEb675f77523">
          <span class="OESZ OESZ_Text OESZG_WEb675f77523 ContentBox">Idioma</span>
         </div>
        </div>
        <div id="WE5dd84af715" class="BaseDiv RHeight OEWEPanel OESK_WEPanel_Default OEGo" style="z-index:4">
         <div class="OESZ OESZ_DivContent OESZG_WE5dd84af715">
          <a href="javascript:loggin()">
           <div class="OECT OECT_Content OECTAbs OEDynTag0">
            <div id="WE45e929cd52" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2">
             <div class="OESZ OESZ_DivContent OESZG_WE45e929cd52">
              <picture>
               <source media="only screen and (max-width: 950px)" srcset="Images/go_icon-WE45e929cd52-66736b49-9f9c-408f-8e1c-7fcd4c7650b2.png" />
               <img src="Images/go_icon-WE45e929cd52.png" class="OESZ OESZ_Img OESZG_WE45e929cd52" alt="" />
              </picture>
             </div>
            </div>
            <div id="WE66637a0e2c" class="BaseDiv RWidth OEWELabel OESK_WELabel_Default" style="z-index:1">
             <div class="OESZ OESZ_DivContent OESZG_WE66637a0e2c">
              <span class="OESZ OESZ_Text OESZG_WE66637a0e2c ContentBox">Ingresar</span>
             </div>
            </div>
           </div>
          </a>
         </div>
        </div>
        <div id="WE549b6b4c6b" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default OEGo" style="z-index:12">
         <div class="OESZ OESZ_DivContent OESZG_WE549b6b4c6b">
          <a href="javascript:lang('-es')">
           <img src="Images/_es-WE526c044191.png" class="OESZ OESZ_Img OESZG_WE549b6b4c6b" alt="" />
          </a>
         </div>
        </div>
        <div id="WE160e673c1f" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default OEGo" style="z-index:10">
         <div class="OESZ OESZ_DivContent OESZG_WE160e673c1f">
          <a href="javascript:lang('-en')">
           <img src="Images/_en-WE160e673c1f.png" class="OESZ OESZ_Img OESZG_WE160e673c1f" alt="" />
          </a>
         </div>
        </div>
        <div id="WE526c044191" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default OEGo" style="z-index:11">
         <div class="OESZ OESZ_DivContent OESZG_WE526c044191">
          <a href="javascript:lang('-pr')">
           <img src="Images/_pr-WE526c044191.png" class="OESZ OESZ_Img OESZG_WE526c044191" alt="" />
          </a>
         </div>
        </div>
       </div>
      </div>
     </div>
     <div id="WEb66dd8e863" class="BaseDiv RBoth OEWEImage OESK_WEImage_Default" style="z-index:2">
      <div class="OESZ OESZ_DivContent OESZG_WEb66dd8e863">
       <picture>
        <source media="only screen and (max-width: 950px)" srcset="Images/bg_ico_2-WEb66dd8e863-66736b49-9f9c-408f-8e1c-7fcd4c7650b2.png" />
        <img src="Images/bg_ico_2-WEb66dd8e863.png" class="OESZ OESZ_Img OESZG_WEb66dd8e863" alt="" />
       </picture>
      </div>
     </div>
    </div>
   </div>
  </div>
  <script type="text/javascript" src="js/loggin.js"></script>
 </body>
</html>