<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="es">
 <head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <meta name="generator" content="openElement (1.57.9)" />
  <link id="openElement" rel="stylesheet" type="text/css" href="WEFiles/Css/v02/openElement.css?v=50491112400" />
  <link id="OETemplate1" rel="stylesheet" type="text/css" href="Templates/Base.css?v=50491112400" />
  <link id="OETemplate2" rel="stylesheet" type="text/css" href="Templates/Canvas%20Businnes%20Model.css?v=50491112400" />
  <link id="OEBase" rel="stylesheet" type="text/css" href="Canvas.css?v=50491112400" />
  <!--[if lte IE 7]>
  <link rel="stylesheet" type="text/css" href="WEFiles/Css/ie7.css?v=50491112400" />
  <![endif]-->
  <script type="text/javascript">
   var WEInfoPage = {"PHPVersion":"phpOK","OEVersion":"1-57-9","PagePath":"Canvas","Culture":"DEFAULT","LanguageCode":"ES","RelativePath":"","RenderMode":"Export","PageAssociatePath":"Canvas","EditorTexts":null};
  </script>
  <script type="text/javascript" src="WEFiles/Client/jQuery/1.10.2.js?v=50491112400"></script>
  <script type="text/javascript" src="WEFiles/Client/jQuery/migrate.js?v=50491112400"></script>
  <script type="text/javascript" src="WEFiles/Client/Common/oe.min.js?v=50491112400"></script>
  <style id="OEScriptManager" type="text/css">
   ::-webkit-scrollbar{width:5px}::-webkit-scrollbar-track{background:#cccccc;border-radius:50px}::-webkit-scrollbar-thumb{background:#00afdb;border-radius:0px}
   .rotate-in-2-cw{-webkit-animation:rotate-in-2-cw .5s cubic-bezier(.25,.46,.45,.94) both;animation:rotate-in-2-cw .5s cubic-bezier(.25,.46,.45,.94) both}
   .slide-in-top{-webkit-animation:slide-in-top .5s cubic-bezier(.25,.46,.45,.94) both;animation:slide-in-top .5s cubic-bezier(.25,.46,.45,.94) both}
   .slide-in-right{-webkit-animation:slide-in-right 1s cubic-bezier(.25,.46,.45,.94) both;animation:slide-in-right 1s cubic-bezier(.25,.46,.45,.94) both}
   
   /* ----------------------------------------------
    * Generated by Animista on 2020-7-26 17:20:15
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */
   
   @-webkit-keyframes rotate-in-2-cw{0%{-webkit-transform:rotate(-45deg);transform:rotate(-45deg);opacity:0}100%{-webkit-transform:rotate(0);transform:rotate(0);opacity:1}}@keyframes rotate-in-2-cw{0%{-webkit-transform:rotate(-45deg);transform:rotate(-45deg);opacity:0}100%{-webkit-transform:rotate(0);transform:rotate(0);opacity:1}}
   /* ----------------------------------------------
    * Generated by Animista on 2020-7-26 17:23:45
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */
   
   @-webkit-keyframes slide-in-top{0%{-webkit-transform:translateY(-1000px);transform:translateY(-1000px);opacity:0}100%{-webkit-transform:translateY(0);transform:translateY(0);opacity:1}}@keyframes slide-in-top{0%{-webkit-transform:translateY(-1000px);transform:translateY(-1000px);opacity:0}100%{-webkit-transform:translateY(0);transform:translateY(0);opacity:1}}
   
   /* ----------------------------------------------
    * Generated by Animista on 2020-7-26 17:25:49
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */
   
   @-webkit-keyframes slide-in-right{0%{-webkit-transform:translateX(1000px);transform:translateX(1000px);opacity:0}100%{-webkit-transform:translateX(0);transform:translateX(0);opacity:1}}@keyframes slide-in-right{0%{-webkit-transform:translateX(1000px);transform:translateX(1000px);opacity:0}100%{-webkit-transform:translateX(0);transform:translateX(0);opacity:1}}
  </style>
  <script type="text/javascript">
   MostrarTarjeta = (i, id) => {
   	var Tarjetas = document.getElementById("WEcb32818414");
   	
   	if (id != null){
   		
   		var TituloVertical = Tarjetas.children[0].children[0].children[0].children[0].children[0].children[1].children[0];
   		var TituloHorizontal = Tarjetas.children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0];
   
   		var texto = Tarjetas.children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[1].children[0];
   		var tips = Tarjetas.children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[2].children[0].children[0].children[0].children[1];
   
   		// Actualizar:
   		TituloVertical.innerText = game_cards[id].titulo;
   		TituloHorizontal.innerText = game_cards[id].titulo;
   		texto.innerText = game_cards[id].detalle;
   		tips.innerText = game_cards[id].tips; 
   
   
   
   
   		color = (a) => {
   
   			switch(a){
   				case 1: return "#c00000"; break;
   				case 2: return "#1e90ff"; break;
   				case 3: return "#32cd32"; break;
   				case 4: return "#c0c000"; break;					
   				case 5: return "#0000cd"; break;					
   				case 6: return "#ff8000"; break;
   
   			}
   
   		}
   
   		Tarjetas.children[0].children[0].children[0].setAttribute("style", "Background:"+color(game_cards[id].tipo))
   	}
   	
   	Tarjetas.style.visibility = (i) ? "visible" : "hidden";
   	Tarjetas.children[0].children[0].className += " rotate-in-2-cw"
   	
   	if (!i) {Tarjetas.children[0].children[0].className = "OECT OECT_Content OECTAbs OEDynTag0";};
   	//setTimeout(() => {MostrarTarjeta(false);}, 15000);
   	
   }
  </script>
  <link rel="preload" as="image" href="WEFiles/Image/WEImage/logo-WE71cb131790.png">
  
  <link rel="Prefetch" as="image" href="">
  
  <!-- 
  audio
  document
  embed
  fetch
  font
  image
  object
  script
  style
  track
  worker
  video
  --><?php
  	if (isset($oeHeaderInlineCode)) echo $oeHeaderInlineCode;
  ?>
 </head>
 <body class="RWAuto" data-gl="{&quot;KeywordsHomeNotInherits&quot;:false}"><?php
  	if (isset($oeStartBodyInlineCode)) echo $oeStartBodyInlineCode;
  ?>
  <form id="XForm" method="post" action="#"></form>
  <div id="XBody" class="BaseDiv RWidth OEPageXbody OESK_XBody_Default" style="z-index:2000">
   <div class="OESZ OESZ_DivContent OESZG_XBody">
    <div class="OESZ OESZ_XBodyHeader OESZG_XBody OECT OECT_Header OECTAbs">
     <div id="WEcb32818414" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2003">
      <div class="OESZ OESZ_DivContent OESZG_WEcb32818414">
       <div class="OECT OECT_Content OECTAbs OEDynTag0">
        <div id="WEe1784fd48a" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OECenterAB rotate-in-2-cw" style="z-index:2001">
         <div class="OESZ OESZ_DivContent OESZG_WEe1784fd48a">
          <div class="OECT OECT_Content OECTAbs OEDynTag0">
           <div id="WE8b9a298b3a" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OECenterAV" style="z-index:2001">
            <div class="OESZ OESZ_DivContent OESZG_WE8b9a298b3a">
             <div class="OECT OECT_Content OECTRel OEDynTag0" style="overflow:hidden">
              <div class="OERelLine OEHAlignL OEVAlignB">
               <div id="WE03baaf7ffe" class="BaseDiv RWidth OEWELabel OESK_WELabel_Default" style="z-index:2001">
                <div class="OESZ OESZ_DivContent OESZG_WE03baaf7ffe">
                 <span class="OESZ OESZ_Text OESZG_WE03baaf7ffe ContentBox">Titulo Tarjeta:</span>
                </div>
               </div>
              </div>
              <div class="OERelLine OEHAlignC OEVAlignB">
               <div id="WEb2b291eb0a" class="BaseDiv RWidth OEWEText OESK_WEText_Default" style="z-index:2002">
                <div class="OESZ OESZ_DivContent OESZG_WEb2b291eb0a">
                 <span class="ContentBox">Todo el texto que llevaría la tarjeta<br />que no se si es corto<br />o si es largo, no importa, hay que escribir, y escribir, y escribir y escribir<br />My multi-line text<br />My multi-line text<br />My multi-line text<br />My multi-line text<br /></span>
                </div>
               </div>
              </div>
              <div class="OERelLine OEHAlignC OEVAlignB">
               <div id="WE7a70bd6e76" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2003">
                <div class="OESZ OESZ_DivContent OESZG_WE7a70bd6e76">
                 <div class="OECT OECT_Content OECTAbs OEDynTag0">
                  <div id="WE9e62367e12" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2002">
                   <div class="OESZ OESZ_DivContent OESZG_WE9e62367e12">
                    <span class="OESZ OESZ_Text OESZG_WE9e62367e12 ContentBox">Tips:</span>
                   </div>
                  </div>
                  <div id="WE2b213dea66" class="BaseDiv RWidth OEWEText OESK_WEText_Default" style="z-index:2001">
                   <div class="OESZ OESZ_DivContent OESZG_WE2b213dea66">
                    <span class="ContentBox">Todo el texto que llevaría la tarjeta<br />que no se si es corto<br />o si es largo, no importa, hay que escribir, y escribir, y escribir y&nbsp;<br /></span>
                   </div>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </div>
           </div>
           <div id="WE7e3f5c075b" class="BaseDiv RWidth OEWELabel OESK_WELabel_Default" style="z-index:2002">
            <div class="OESZ OESZ_DivContent OESZG_WE7e3f5c075b">
             <span class="OESZ OESZ_Text OESZG_WE7e3f5c075b ContentBox">Titulo Tarjeta:</span>
            </div>
           </div>
          </div>
         </div>
        </div>
       </div>
      </div>
     </div>
     <div id="WE4a65a86bf9" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:1001">
      <div class="OESZ OESZ_DivContent OESZG_WE4a65a86bf9">
       <img src="WEFiles/Image/WEImage/UserDefault-WE4a65a86bf9.png" class="OESZ OESZ_Img OESZG_WE4a65a86bf9" alt="" />
      </div>
     </div>
     <div id="WE71cb131790" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:1">
      <div class="OESZ OESZ_DivContent OESZG_WE71cb131790">
       <picture>
        <source media="only screen and (max-width: 1199px)" srcset="WEFiles/Image/WEImage/logo-WE71cb131790-SmartPhone-1.png" />
        <img src="WEFiles/Image/WEImage/logo-WE71cb131790.png" class="OESZ OESZ_Img OESZG_WE71cb131790" alt="" />
       </picture>
      </div>
     </div>
     <div id="WE8edb8be0ba" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
      <div class="OESZ OESZ_DivContent OESZG_WE8edb8be0ba">
       <span class="OESZ OESZ_Text OESZG_WE8edb8be0ba ContentBox">Nombre del Jugador Completo</span>
      </div>
     </div>
     <div id="WE64b8c1a397" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2002">
      <div class="OESZ OESZ_DivContent OESZG_WE64b8c1a397">
       <span class="OESZ OESZ_Text OESZG_WE64b8c1a397 ContentBox">Equipo Perteneciente</span>
      </div>
     </div>
    </div>
    <div class="OESZ_Wrap_Columns OESZ_Wrap_Columns_NoRight">
     <div class="OESZ OESZ_XBodyLeftColumn OESZG_XBody OECT OECT_LeftColumn OECTAbs">
      <div id="WEe94ea83c6f" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OEGo" style="z-index:1">
       <div class="OESZ OESZ_DivContent OESZG_WEe94ea83c6f">
        <a href="javascript:CambiarPartida();">
         <div class="OECT OECT_Content OECTAbs OEDynTag0">
          <div id="WE9917ebf0d3" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2">
           <div class="OESZ OESZ_DivContent OESZG_WE9917ebf0d3">
            <img src="WEFiles/Image/WEImage/path4634-WE9917ebf0d3.png" class="OESZ OESZ_Img OESZG_WE9917ebf0d3" alt="" />
           </div>
          </div>
          <div id="WE9470216102" class="BaseDiv RWidth OEWELabel OESK_WELabel_Default" style="z-index:1">
           <div class="OESZ OESZ_DivContent OESZG_WE9470216102">
            <span class="OESZ OESZ_Text OESZG_WE9470216102 ContentBox">Estado Partida<br /></span>
           </div>
          </div>
         </div>
        </a>
       </div>
      </div>
      <div id="WEb8644db9e4" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OEGo" style="z-index:2">
       <div class="OESZ OESZ_DivContent OESZG_WEb8644db9e4">
        <a href="javascript:CambiarCanvas();">
         <div class="OECT OECT_Content OECTAbs OEDynTag0">
          <div id="WE3ad8c0d37a" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2">
           <div class="OESZ OESZ_DivContent OESZG_WE3ad8c0d37a">
            <img src="WEFiles/Image/WEImage/cambas-WE3ad8c0d37a.png" class="OESZ OESZ_Img OESZG_WE3ad8c0d37a" alt="" />
           </div>
          </div>
          <div id="WE9f8e92fd77" class="BaseDiv RWidth OEWELabel OESK_WELabel_Default" style="z-index:1">
           <div class="OESZ OESZ_DivContent OESZG_WE9f8e92fd77">
            <span class="OESZ OESZ_Text OESZG_WE9f8e92fd77 ContentBox">Canvas Model Business<br /></span>
           </div>
          </div>
         </div>
        </a>
       </div>
      </div>
      <div id="WE2df3a0ab3b" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OEGo" style="z-index:3">
       <div class="OESZ OESZ_DivContent OESZG_WE2df3a0ab3b">
        <a href="javascript:CambiarDash();">
         <div class="OECT OECT_Content OECTAbs OEDynTag0">
          <div id="WE9f20acf474" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2">
           <div class="OESZ OESZ_DivContent OESZG_WE9f20acf474">
            <img src="WEFiles/Image/WEImage/company-WE9f20acf474.png" class="OESZ OESZ_Img OESZG_WE9f20acf474" alt="" />
           </div>
          </div>
          <div id="WE203e288d9d" class="BaseDiv RWidth OEWELabel OESK_WELabel_Default" style="z-index:1">
           <div class="OESZ OESZ_DivContent OESZG_WE203e288d9d">
            <span class="OESZ OESZ_Text OESZG_WE203e288d9d ContentBox">Company Status<br /></span>
           </div>
          </div>
         </div>
        </a>
       </div>
      </div>
     </div>
     <div class="OESZ OESZ_XBodyContent OESZG_XBody OECT OECT_Content OECTAbs">
      <div id="WE0b12853407" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default  slide-in-right" style="z-index:2002">
       <div class="OESZ OESZ_DivContent OESZG_WE0b12853407">
        <div class="OECT OECT_Content OECTRel OEDynTag0">
         <div class="OERelLine OEHAlignC OEVAlignB">
          <div id="WE13aadfe663" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OECenterRH" style="z-index:2013">
           <div class="OESZ OESZ_DivContent OESZG_WE13aadfe663">
            <div class="OECT OECT_Content OECTAbs OEDynTag0">
             <div id="WEb3f08394ca" class="BaseDiv RWidth OEWELabel OESK_WELabel_Default" style="z-index:2001">
              <div class="OESZ OESZ_DivContent OESZG_WEb3f08394ca">
               <span class="OESZ OESZ_Text OESZG_WEb3f08394ca ContentBox">Avaliable Cards</span>
              </div>
             </div>
            </div>
           </div>
          </div>
         </div>
         <div class="OERelLine OEHAlignC OEVAlignT">
          <div id="WE_CARD_demo1" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2002">
           <div class="OESZ OESZ_DivContent OESZG_WE_CARD_demo1">
            <main id="Card1" draggable="true" ondragstart="drag(event)">
             <div class="OECT OECT_Content OECTAbs OEDynTag0">
              <div id="WE600431a48a" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
               <div class="OESZ OESZ_DivContent OESZG_WE600431a48a">
                <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                 <div id="WE3871e97495" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                  <div class="OESZ OESZ_DivContent OESZG_WE3871e97495">
                   <a href="javascript:alert('test');">
                    <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WE3871e97495" alt="" />
                   </a>
                  </div>
                 </div>
                 <div id="WE854a4c6608" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WE854a4c6608">
                   <span class="OESZ OESZ_Text OESZG_WE854a4c6608 ContentBox">Titulo Card Demo 1<br /></span>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </main>
           </div>
          </div><div id="WEa19b3e9496" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2002">
           <div class="OESZ OESZ_DivContent OESZG_WEa19b3e9496">
            <main id="Card20" draggable="true" ondragstart="drag(event)">
             <div class="OECT OECT_Content OECTAbs OEDynTag0">
              <div id="WE9aa95f04f1" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
               <div class="OESZ OESZ_DivContent OESZG_WE9aa95f04f1">
                <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                 <div id="WEc26b1fa455" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                  <div class="OESZ OESZ_DivContent OESZG_WEc26b1fa455">
                   <a href="javascript:alert('test');">
                    <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WEc26b1fa455" alt="" />
                   </a>
                  </div>
                 </div>
                 <div id="WEcc4275897f" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WEcc4275897f">
                   <span class="OESZ OESZ_Text OESZG_WEcc4275897f ContentBox">Titulo Card Demo 1<br /></span>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </main>
           </div>
          </div><div id="WE980fb9c2a5" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2003">
           <div class="OESZ OESZ_DivContent OESZG_WE980fb9c2a5">
            <main id="Card21" draggable="true" ondragstart="drag(event)">
             <div class="OECT OECT_Content OECTAbs OEDynTag0">
              <div id="WE07f7cf90a4" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
               <div class="OESZ OESZ_DivContent OESZG_WE07f7cf90a4">
                <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                 <div id="WEa9fb890e09" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                  <div class="OESZ OESZ_DivContent OESZG_WEa9fb890e09">
                   <a href="javascript:alert('test');">
                    <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WEa9fb890e09" alt="" />
                   </a>
                  </div>
                 </div>
                 <div id="WE649f838144" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WE649f838144">
                   <span class="OESZ OESZ_Text OESZG_WE649f838144 ContentBox">Titulo Card Demo 1<br /></span>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </main>
           </div>
          </div><div id="WEbb996faad8" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2004">
           <div class="OESZ OESZ_DivContent OESZG_WEbb996faad8">
            <main id="Card32" draggable="true" ondragstart="drag(event)">
             <div class="OECT OECT_Content OECTAbs OEDynTag0">
              <div id="WE86f89c7d60" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
               <div class="OESZ OESZ_DivContent OESZG_WE86f89c7d60">
                <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                 <div id="WE0fddb928b4" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                  <div class="OESZ OESZ_DivContent OESZG_WE0fddb928b4">
                   <a href="javascript:alert('test');">
                    <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WE0fddb928b4" alt="" />
                   </a>
                  </div>
                 </div>
                 <div id="WEe29ccd68c0" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WEe29ccd68c0">
                   <span class="OESZ OESZ_Text OESZG_WEe29ccd68c0 ContentBox">Titulo Card Demo 1<br /></span>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </main>
           </div>
          </div><div id="WE3cc132a49c" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2005">
           <div class="OESZ OESZ_DivContent OESZG_WE3cc132a49c">
            <main id="Car331" draggable="true" ondragstart="drag(event)">
             <div class="OECT OECT_Content OECTAbs OEDynTag0">
              <div id="WE224587bd4f" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
               <div class="OESZ OESZ_DivContent OESZG_WE224587bd4f">
                <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                 <div id="WE06ce20920f" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                  <div class="OESZ OESZ_DivContent OESZG_WE06ce20920f">
                   <a href="javascript:alert('test');">
                    <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WE06ce20920f" alt="" />
                   </a>
                  </div>
                 </div>
                 <div id="WE2499bc0bc5" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WE2499bc0bc5">
                   <span class="OESZ OESZ_Text OESZG_WE2499bc0bc5 ContentBox">Titulo Card Demo 1<br /></span>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </main>
           </div>
          </div><div id="WE6c7b021071" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2006">
           <div class="OESZ OESZ_DivContent OESZG_WE6c7b021071">
            <main id="Card34" draggable="true" ondragstart="drag(event)">
             <div class="OECT OECT_Content OECTAbs OEDynTag0">
              <div id="WE9249cbbf4d" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
               <div class="OESZ OESZ_DivContent OESZG_WE9249cbbf4d">
                <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                 <div id="WE77736ab900" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                  <div class="OESZ OESZ_DivContent OESZG_WE77736ab900">
                   <a href="javascript:alert('test');">
                    <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WE77736ab900" alt="" />
                   </a>
                  </div>
                 </div>
                 <div id="WE5aaa7f08f5" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WE5aaa7f08f5">
                   <span class="OESZ OESZ_Text OESZG_WE5aaa7f08f5 ContentBox">Titulo Card Demo 1<br /></span>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </main>
           </div>
          </div><div id="WEa837638e21" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2007">
           <div class="OESZ OESZ_DivContent OESZG_WEa837638e21">
            <main id="Car35" draggable="true" ondragstart="drag(event)">
             <div class="OECT OECT_Content OECTAbs OEDynTag0">
              <div id="WE10a68a4ef2" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
               <div class="OESZ OESZ_DivContent OESZG_WE10a68a4ef2">
                <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                 <div id="WE1a593bd89b" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                  <div class="OESZ OESZ_DivContent OESZG_WE1a593bd89b">
                   <a href="javascript:alert('test');">
                    <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WE1a593bd89b" alt="" />
                   </a>
                  </div>
                 </div>
                 <div id="WE18fb12ec6a" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WE18fb12ec6a">
                   <span class="OESZ OESZ_Text OESZG_WE18fb12ec6a ContentBox">Titulo Card Demo 1<br /></span>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </main>
           </div>
          </div><div id="WEe2b6266da9" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2008">
           <div class="OESZ OESZ_DivContent OESZG_WEe2b6266da9">
            <main id="Car36" draggable="true" ondragstart="drag(event)">
             <div class="OECT OECT_Content OECTAbs OEDynTag0">
              <div id="WEb82604c393" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
               <div class="OESZ OESZ_DivContent OESZG_WEb82604c393">
                <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                 <div id="WE14ae447c2d" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                  <div class="OESZ OESZ_DivContent OESZG_WE14ae447c2d">
                   <a href="javascript:alert('test');">
                    <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WE14ae447c2d" alt="" />
                   </a>
                  </div>
                 </div>
                 <div id="WEde4cca319c" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WEde4cca319c">
                   <span class="OESZ OESZ_Text OESZG_WEde4cca319c ContentBox">Titulo Card Demo 1<br /></span>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </main>
           </div>
          </div><div id="WE1745ec6f83" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2009">
           <div class="OESZ OESZ_DivContent OESZG_WE1745ec6f83">
            <main id="Car37" draggable="true" ondragstart="drag(event)">
             <div class="OECT OECT_Content OECTAbs OEDynTag0">
              <div id="WEa593bb37af" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
               <div class="OESZ OESZ_DivContent OESZG_WEa593bb37af">
                <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                 <div id="WEd1e4041a40" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                  <div class="OESZ OESZ_DivContent OESZG_WEd1e4041a40">
                   <a href="javascript:alert('test');">
                    <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WEd1e4041a40" alt="" />
                   </a>
                  </div>
                 </div>
                 <div id="WE6260aad157" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WE6260aad157">
                   <span class="OESZ OESZ_Text OESZG_WE6260aad157 ContentBox">Titulo Card Demo 1<br /></span>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </main>
           </div>
          </div><div id="WEfec083a4d9" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2010">
           <div class="OESZ OESZ_DivContent OESZG_WEfec083a4d9">
            <main id="Car38" draggable="true" ondragstart="drag(event)">
             <div class="OECT OECT_Content OECTAbs OEDynTag0">
              <div id="WE77cb87acba" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
               <div class="OESZ OESZ_DivContent OESZG_WE77cb87acba">
                <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                 <div id="WEade50f94ce" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                  <div class="OESZ OESZ_DivContent OESZG_WEade50f94ce">
                   <a href="javascript:alert('test');">
                    <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WEade50f94ce" alt="" />
                   </a>
                  </div>
                 </div>
                 <div id="WE252e345313" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WE252e345313">
                   <span class="OESZ OESZ_Text OESZG_WE252e345313 ContentBox">Titulo Card Demo 1<br /></span>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </main>
           </div>
          </div><div id="WEdeaed823c1" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2011">
           <div class="OESZ OESZ_DivContent OESZG_WEdeaed823c1">
            <main id="Car39" draggable="true" ondragstart="drag(event)">
             <div class="OECT OECT_Content OECTAbs OEDynTag0">
              <div id="WE455736a507" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
               <div class="OESZ OESZ_DivContent OESZG_WE455736a507">
                <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                 <div id="WEbbeca54a1d" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                  <div class="OESZ OESZ_DivContent OESZG_WEbbeca54a1d">
                   <a href="javascript:alert('test');">
                    <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WEbbeca54a1d" alt="" />
                   </a>
                  </div>
                 </div>
                 <div id="WE8db6b6b8e6" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WE8db6b6b8e6">
                   <span class="OESZ OESZ_Text OESZG_WE8db6b6b8e6 ContentBox">Titulo Card Demo 1<br /></span>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </main>
           </div>
          </div><div id="WE7d4795b265" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2012">
           <div class="OESZ OESZ_DivContent OESZG_WE7d4795b265">
            <main id="Car70" draggable="true" ondragstart="drag(event)">
             <div class="OECT OECT_Content OECTAbs OEDynTag0">
              <div id="WEee86bae857" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
               <div class="OESZ OESZ_DivContent OESZG_WEee86bae857">
                <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                 <div id="WE76e7ed6099" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                  <div class="OESZ OESZ_DivContent OESZG_WE76e7ed6099">
                   <a href="javascript:alert('test');">
                    <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WE76e7ed6099" alt="" />
                   </a>
                  </div>
                 </div>
                 <div id="WEdfc1ad67f7" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WEdfc1ad67f7">
                   <span class="OESZ OESZ_Text OESZG_WEdfc1ad67f7 ContentBox">Titulo Card Demo 1<br /></span>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </main>
           </div>
          </div>
         </div>
        </div>
       </div>
      </div>
      <div id="WE3395e00991" class="BaseDiv RHeight OEWEPanel OESK_WEPanel_Default  slide-in-top" style="z-index:2001">
       <div class="OESZ OESZ_DivContent OESZG_WE3395e00991">
        <div class="OECT OECT_Content OECTRel OEDynTag0">
         <div class="OERelLine OEHAlignL OEVAlignT">
          <div id="WE245cf2c7e5" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
           <div class="OESZ OESZ_DivContent OESZG_WE245cf2c7e5">
            <div class="OECT OECT_Content OECTAbs OEDynTag0">
             <div id="WE_KeyPatner" class="BaseDiv RNone OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
              <div class="OESZ OESZ_DivContent OESZG_WE_KeyPatner">
               <div class="OECT OECT_Content OECTRel OEDynTag0">
                <div class="OERelLine OEHAlignC OEVAlignB">
                 <div id="WE78728e7b66" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OECenterRH" style="z-index:2004">
                  <div class="OESZ OESZ_DivContent OESZG_WE78728e7b66">
                   <div class="OECT OECT_Content OECTAbs OEDynTag0">
                    <div id="WE09be91587c" class="BaseDiv RBoth OEWECadre OESK_WECadre_Default" style="z-index:2003">
                     <div class="OESZ OESZ_DivContent OESZG_WE09be91587c">
                      <div class="OESZ OESZ_Top OESZG_WE09be91587c"></div>
                      <div class="OESZ OESZ_Content OESZG_WE09be91587c"></div>
                      <div class="OESZ OESZ_Bottom OESZG_WE09be91587c"></div>
                     </div>
                    </div>
                    <div id="WE902194113e" class="BaseDiv RWidth OEWELabel OESK_WELabel_Default" style="z-index:2001">
                     <div class="OESZ OESZ_DivContent OESZG_WE902194113e">
                      <span class="OESZ OESZ_Text OESZG_WE902194113e ContentBox">Key Partner</span>
                     </div>
                    </div>
                    <div id="WEea96b64b3a" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                     <div class="OESZ OESZ_DivContent OESZG_WEea96b64b3a">
                      <img src="WEFiles/Image/WEImage/g3343-WEea96b64b3a.png" class="OESZ OESZ_Img OESZG_WEea96b64b3a" alt="" />
                     </div>
                    </div>
                   </div>
                  </div>
                 </div>
                </div>
                <div class="OERelLine OEHAlignC OEVAlignT">
                 <div id="WE92a8971e66" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2004">
                  <div class="OESZ OESZ_DivContent OESZG_WE92a8971e66">
                   <main id="Card10" draggable="true" ondragstart="drag(event)">
                    <div class="OECT OECT_Content OECTAbs OEDynTag0">
                     <div id="WE3412181c57" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
                      <div class="OESZ OESZ_DivContent OESZG_WE3412181c57">
                       <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                        <div id="WE42ba871ac5" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                         <div class="OESZ OESZ_DivContent OESZG_WE42ba871ac5">
                          <a href="javascript:alert('test');">
                           <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WE42ba871ac5" alt="" />
                          </a>
                         </div>
                        </div>
                        <div id="WE3b99eeb6de" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                         <div class="OESZ OESZ_DivContent OESZG_WE3b99eeb6de">
                          <span class="OESZ OESZ_Text OESZG_WE3b99eeb6de ContentBox">Titulo Card Demo 1<br /></span>
                         </div>
                        </div>
                       </div>
                      </div>
                     </div>
                    </div>
                   </main>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </div>
           </div>
          </div><div id="WE3f2ab97132" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2002">
           <div class="OESZ OESZ_DivContent OESZG_WE3f2ab97132">
            <div class="OECT OECT_Content OECTRel OEDynTag0">
             <div class="OERelLine OEHAlignL OEVAlignB">
              <div id="WE1591dcf79c" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
               <div class="OESZ OESZ_DivContent OESZG_WE1591dcf79c">
                <div class="OECT OECT_Content OECTAbs OEDynTag0">
                 <div id="WE_KeyActivities" class="BaseDiv RNone OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WE_KeyActivities">
                   <div class="OECT OECT_Content OECTRel OEDynTag0">
                    <div class="OERelLine OEHAlignC OEVAlignB">
                     <div id="WE1c280e9b2d" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OECenterRH" style="z-index:2002">
                      <div class="OESZ OESZ_DivContent OESZG_WE1c280e9b2d">
                       <div class="OECT OECT_Content OECTAbs OEDynTag0">
                        <div id="WE10fab00a86" class="BaseDiv RBoth OEWECadre OESK_WECadre_Default" style="z-index:2003">
                         <div class="OESZ OESZ_DivContent OESZG_WE10fab00a86">
                          <div class="OESZ OESZ_Top OESZG_WE10fab00a86"></div>
                          <div class="OESZ OESZ_Content OESZG_WE10fab00a86"></div>
                          <div class="OESZ OESZ_Bottom OESZG_WE10fab00a86"></div>
                         </div>
                        </div>
                        <div id="WE737a6a5bc0" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                         <div class="OESZ OESZ_DivContent OESZG_WE737a6a5bc0">
                          <img src="WEFiles/Image/WEImage/g3331-WE737a6a5bc0.png" class="OESZ OESZ_Img OESZG_WE737a6a5bc0" alt="" />
                         </div>
                        </div>
                        <div id="WEdd2cfeb230" class="BaseDiv RWidth OEWELabel OESK_WELabel_Default" style="z-index:2001">
                         <div class="OESZ OESZ_DivContent OESZG_WEdd2cfeb230">
                          <span class="OESZ OESZ_Text OESZG_WEdd2cfeb230 ContentBox">Key Ativities</span>
                         </div>
                        </div>
                       </div>
                      </div>
                     </div>
                    </div>
                    <div class="OERelLine OEHAlignC OEVAlignT">
                     <div id="WE641bddf0ae" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2002">
                      <div class="OESZ OESZ_DivContent OESZG_WE641bddf0ae">
                       <main id="Card2" draggable="true" ondragstart="drag(event)">
                        <div class="OECT OECT_Content OECTAbs OEDynTag0">
                         <div id="WE0b2158b0cd" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
                          <div class="OESZ OESZ_DivContent OESZG_WE0b2158b0cd">
                           <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                            <div id="WEe622c5930c" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                             <div class="OESZ OESZ_DivContent OESZG_WEe622c5930c">
                              <a href="javascript:alert('test');">
                               <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WEe622c5930c" alt="" />
                              </a>
                             </div>
                            </div>
                            <div id="WEb9f8588e1a" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                             <div class="OESZ OESZ_DivContent OESZG_WEb9f8588e1a">
                              <span class="OESZ OESZ_Text OESZG_WEb9f8588e1a ContentBox">Titulo Card Demo 1<br /></span>
                             </div>
                            </div>
                           </div>
                          </div>
                         </div>
                        </div>
                       </main>
                      </div>
                     </div>
                    </div>
                   </div>
                  </div>
                 </div>
                </div>
               </div>
              </div><div id="WE5c711c1dca" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2002">
               <div class="OESZ OESZ_DivContent OESZG_WE5c711c1dca">
                <div class="OECT OECT_Content OECTAbs OEDynTag0">
                 <div id="WE_KeyResources" class="BaseDiv RNone OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WE_KeyResources">
                   <div class="OECT OECT_Content OECTRel OEDynTag0">
                    <div class="OERelLine OEHAlignC OEVAlignB">
                     <div id="WE1b8f431b0e" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OECenterRH" style="z-index:2002">
                      <div class="OESZ OESZ_DivContent OESZG_WE1b8f431b0e">
                       <div class="OECT OECT_Content OECTAbs OEDynTag0">
                        <div id="WEa01f121909" class="BaseDiv RBoth OEWECadre OESK_WECadre_Default" style="z-index:2003">
                         <div class="OESZ OESZ_DivContent OESZG_WEa01f121909">
                          <div class="OESZ OESZ_Top OESZG_WEa01f121909"></div>
                          <div class="OESZ OESZ_Content OESZG_WEa01f121909"></div>
                          <div class="OESZ OESZ_Bottom OESZG_WEa01f121909"></div>
                         </div>
                        </div>
                        <div id="WE68bc5b031c" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                         <div class="OESZ OESZ_DivContent OESZG_WE68bc5b031c">
                          <img src="WEFiles/Image/WEImage/g3335-WE68bc5b031c.png" class="OESZ OESZ_Img OESZG_WE68bc5b031c" alt="" />
                         </div>
                        </div>
                        <div id="WEca771210ef" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                         <div class="OESZ OESZ_DivContent OESZG_WEca771210ef">
                          <span class="OESZ OESZ_Text OESZG_WEca771210ef ContentBox">Key Resources</span>
                         </div>
                        </div>
                       </div>
                      </div>
                     </div>
                    </div>
                    <div class="OERelLine OEHAlignC OEVAlignT">
                     <div id="WEc3f2c2cf10" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
                      <div class="OESZ OESZ_DivContent OESZG_WEc3f2c2cf10">
                       <main id="Card6" draggable="true" ondragstart="drag(event)">
                        <div class="OECT OECT_Content OECTAbs OEDynTag0">
                         <div id="WEb5109ca568" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
                          <div class="OESZ OESZ_DivContent OESZG_WEb5109ca568">
                           <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                            <div id="WE8637d92563" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                             <div class="OESZ OESZ_DivContent OESZG_WE8637d92563">
                              <a href="javascript:alert('test');">
                               <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WE8637d92563" alt="" />
                              </a>
                             </div>
                            </div>
                            <div id="WE55f5acb311" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                             <div class="OESZ OESZ_DivContent OESZG_WE55f5acb311">
                              <span class="OESZ OESZ_Text OESZG_WE55f5acb311 ContentBox">Titulo Card Demo 1<br /></span>
                             </div>
                            </div>
                           </div>
                          </div>
                         </div>
                        </div>
                       </main>
                      </div>
                     </div>
                    </div>
                   </div>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </div>
           </div>
          </div><div id="WE37a71a9d9e" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2003">
           <div class="OESZ OESZ_DivContent OESZG_WE37a71a9d9e">
            <div class="OECT OECT_Content OECTAbs OEDynTag0">
             <div id="WE_ValuePropositions" class="BaseDiv RNone OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
              <div class="OESZ OESZ_DivContent OESZG_WE_ValuePropositions">
               <div class="OECT OECT_Content OECTRel OEDynTag0">
                <div class="OERelLine OEHAlignC OEVAlignB">
                 <div id="WEce9ad384f1" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OECenterRH" style="z-index:2002">
                  <div class="OESZ OESZ_DivContent OESZG_WEce9ad384f1">
                   <div class="OECT OECT_Content OECTAbs OEDynTag0">
                    <div id="WE28b68f0122" class="BaseDiv RBoth OEWECadre OESK_WECadre_Default" style="z-index:2003">
                     <div class="OESZ OESZ_DivContent OESZG_WE28b68f0122">
                      <div class="OESZ OESZ_Top OESZG_WE28b68f0122"></div>
                      <div class="OESZ OESZ_Content OESZG_WE28b68f0122"></div>
                      <div class="OESZ OESZ_Bottom OESZG_WE28b68f0122"></div>
                     </div>
                    </div>
                    <div id="WE64c0c51ee3" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                     <div class="OESZ OESZ_DivContent OESZG_WE64c0c51ee3">
                      <img src="WEFiles/Image/WEImage/g3327-WE64c0c51ee3.png" class="OESZ OESZ_Img OESZG_WE64c0c51ee3" alt="" />
                     </div>
                    </div>
                    <div id="WE5b63596e93" class="BaseDiv RWidth OEWELabel OESK_WELabel_Default" style="z-index:2001">
                     <div class="OESZ OESZ_DivContent OESZG_WE5b63596e93">
                      <span class="OESZ OESZ_Text OESZG_WE5b63596e93 ContentBox">Value Propositions</span>
                     </div>
                    </div>
                   </div>
                  </div>
                 </div>
                </div>
                <div class="OERelLine OEHAlignC OEVAlignT">
                 <div id="WE44652c3461" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2002">
                  <div class="OESZ OESZ_DivContent OESZG_WE44652c3461">
                   <main id="Card3" draggable="true" ondragstart="drag(event)">
                    <div class="OECT OECT_Content OECTAbs OEDynTag0">
                     <div id="WEb7e37a5086" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
                      <div class="OESZ OESZ_DivContent OESZG_WEb7e37a5086">
                       <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                        <div id="WEf3ce9bab33" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                         <div class="OESZ OESZ_DivContent OESZG_WEf3ce9bab33">
                          <a href="javascript:alert('test');">
                           <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WEf3ce9bab33" alt="" />
                          </a>
                         </div>
                        </div>
                        <div id="WE3f50217d1d" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                         <div class="OESZ OESZ_DivContent OESZG_WE3f50217d1d">
                          <span class="OESZ OESZ_Text OESZG_WE3f50217d1d ContentBox">Titulo Card Demo 1<br /></span>
                         </div>
                        </div>
                       </div>
                      </div>
                     </div>
                    </div>
                   </main>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </div>
           </div>
          </div><div id="WEaffbe159f1" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2004">
           <div class="OESZ OESZ_DivContent OESZG_WEaffbe159f1">
            <div class="OECT OECT_Content OECTRel OEDynTag0">
             <div class="OERelLine OEHAlignL OEVAlignB">
              <div id="WE7125614e3c" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
               <div class="OESZ OESZ_DivContent OESZG_WE7125614e3c">
                <div class="OECT OECT_Content OECTAbs OEDynTag0">
                 <div id="WE_CustomerRelationship" class="BaseDiv RNone OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WE_CustomerRelationship">
                   <div class="OECT OECT_Content OECTRel OEDynTag0">
                    <div class="OERelLine OEHAlignC OEVAlignB">
                     <div id="WEf744e71eb0" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OECenterRH" style="z-index:2002">
                      <div class="OESZ OESZ_DivContent OESZG_WEf744e71eb0">
                       <div class="OECT OECT_Content OECTAbs OEDynTag0">
                        <div id="WE2d5c3bf54a" class="BaseDiv RBoth OEWECadre OESK_WECadre_Default" style="z-index:2003">
                         <div class="OESZ OESZ_DivContent OESZG_WE2d5c3bf54a">
                          <div class="OESZ OESZ_Top OESZG_WE2d5c3bf54a"></div>
                          <div class="OESZ OESZ_Content OESZG_WE2d5c3bf54a"></div>
                          <div class="OESZ OESZ_Bottom OESZG_WE2d5c3bf54a"></div>
                         </div>
                        </div>
                        <div id="WE5b3fc60b8f" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                         <div class="OESZ OESZ_DivContent OESZG_WE5b3fc60b8f">
                          <img src="WEFiles/Image/WEImage/g3323-WE5b3fc60b8f.png" class="OESZ OESZ_Img OESZG_WE5b3fc60b8f" alt="" />
                         </div>
                        </div>
                        <div id="WEd98ff5c1d5" class="BaseDiv RWidth OEWELabel OESK_WELabel_Default" style="z-index:2001">
                         <div class="OESZ OESZ_DivContent OESZG_WEd98ff5c1d5">
                          <span class="OESZ OESZ_Text OESZG_WEd98ff5c1d5 ContentBox">Customer Relationships</span>
                         </div>
                        </div>
                       </div>
                      </div>
                     </div>
                    </div>
                    <div class="OERelLine OEHAlignC OEVAlignT">
                     <div id="WE26a17706ed" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2002">
                      <div class="OESZ OESZ_DivContent OESZG_WE26a17706ed">
                       <main id="Card4" draggable="true" ondragstart="drag(event)">
                        <div class="OECT OECT_Content OECTAbs OEDynTag0">
                         <div id="WEf5794e0bac" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
                          <div class="OESZ OESZ_DivContent OESZG_WEf5794e0bac">
                           <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                            <div id="WE31f5c8f127" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                             <div class="OESZ OESZ_DivContent OESZG_WE31f5c8f127">
                              <a href="javascript:alert('test');">
                               <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WE31f5c8f127" alt="" />
                              </a>
                             </div>
                            </div>
                            <div id="WEa774a9dfc2" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                             <div class="OESZ OESZ_DivContent OESZG_WEa774a9dfc2">
                              <span class="OESZ OESZ_Text OESZG_WEa774a9dfc2 ContentBox">Titulo Card Demo 1<br /></span>
                             </div>
                            </div>
                           </div>
                          </div>
                         </div>
                        </div>
                       </main>
                      </div>
                     </div>
                    </div>
                   </div>
                  </div>
                 </div>
                </div>
               </div>
              </div><div id="WE8adbb4d792" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2002">
               <div class="OESZ OESZ_DivContent OESZG_WE8adbb4d792">
                <div class="OECT OECT_Content OECTAbs OEDynTag0">
                 <div id="WE_Channels" class="BaseDiv RNone OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WE_Channels">
                   <div class="OECT OECT_Content OECTRel OEDynTag0">
                    <div class="OERelLine OEHAlignC OEVAlignB">
                     <div id="WEa667038531" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OECenterRH" style="z-index:2002">
                      <div class="OESZ OESZ_DivContent OESZG_WEa667038531">
                       <div class="OECT OECT_Content OECTAbs OEDynTag0">
                        <div id="WEed8af39936" class="BaseDiv RBoth OEWECadre OESK_WECadre_Default" style="z-index:2003">
                         <div class="OESZ OESZ_DivContent OESZG_WEed8af39936">
                          <div class="OESZ OESZ_Top OESZG_WEed8af39936"></div>
                          <div class="OESZ OESZ_Content OESZG_WEed8af39936"></div>
                          <div class="OESZ OESZ_Bottom OESZG_WEed8af39936"></div>
                         </div>
                        </div>
                        <div id="WEd7bc7354d0" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                         <div class="OESZ OESZ_DivContent OESZG_WEd7bc7354d0">
                          <img src="WEFiles/Image/WEImage/g3319-WEd7bc7354d0.png" class="OESZ OESZ_Img OESZG_WEd7bc7354d0" alt="" />
                         </div>
                        </div>
                        <div id="WE60a0062b80" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                         <div class="OESZ OESZ_DivContent OESZG_WE60a0062b80">
                          <span class="OESZ OESZ_Text OESZG_WE60a0062b80 ContentBox">Channels</span>
                         </div>
                        </div>
                       </div>
                      </div>
                     </div>
                    </div>
                    <div class="OERelLine OEHAlignC OEVAlignT">
                     <div id="WEf3287a53ae" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
                      <div class="OESZ OESZ_DivContent OESZG_WEf3287a53ae">
                       <main id="Card7" draggable="true" ondragstart="drag(event)">
                        <div class="OECT OECT_Content OECTAbs OEDynTag0">
                         <div id="WEa6b12d1848" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
                          <div class="OESZ OESZ_DivContent OESZG_WEa6b12d1848">
                           <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                            <div id="WE2ca2aeca74" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                             <div class="OESZ OESZ_DivContent OESZG_WE2ca2aeca74">
                              <a href="javascript:alert('test');">
                               <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WE2ca2aeca74" alt="" />
                              </a>
                             </div>
                            </div>
                            <div id="WE001656da21" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                             <div class="OESZ OESZ_DivContent OESZG_WE001656da21">
                              <span class="OESZ OESZ_Text OESZG_WE001656da21 ContentBox">Titulo Card Demo 1<br /></span>
                             </div>
                            </div>
                           </div>
                          </div>
                         </div>
                        </div>
                       </main>
                      </div>
                     </div>
                    </div>
                   </div>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </div>
           </div>
          </div><div id="WEf8f77e31af" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2005">
           <div class="OESZ OESZ_DivContent OESZG_WEf8f77e31af">
            <div class="OECT OECT_Content OECTAbs OEDynTag0">
             <div id="WE_CustomersSegments" class="BaseDiv RNone OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
              <div class="OESZ OESZ_DivContent OESZG_WE_CustomersSegments">
               <div class="OECT OECT_Content OECTRel OEDynTag0">
                <div class="OERelLine OEHAlignC OEVAlignB">
                 <div id="WEe839dcfcdd" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OECenterRH" style="z-index:2004">
                  <div class="OESZ OESZ_DivContent OESZG_WEe839dcfcdd">
                   <div class="OECT OECT_Content OECTAbs OEDynTag0">
                    <div id="WEd2589c78d8" class="BaseDiv RBoth OEWECadre OESK_WECadre_Default" style="z-index:2003">
                     <div class="OESZ OESZ_DivContent OESZG_WEd2589c78d8">
                      <div class="OESZ OESZ_Top OESZG_WEd2589c78d8"></div>
                      <div class="OESZ OESZ_Content OESZG_WEd2589c78d8"></div>
                      <div class="OESZ OESZ_Bottom OESZG_WEd2589c78d8"></div>
                     </div>
                    </div>
                    <div id="WE994f84a011" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                     <div class="OESZ OESZ_DivContent OESZG_WE994f84a011">
                      <img src="WEFiles/Image/WEImage/g3315-WE994f84a011.png" class="OESZ OESZ_Img OESZG_WE994f84a011" alt="" />
                     </div>
                    </div>
                    <div id="WEe26293ffc4" class="BaseDiv RWidth OEWELabel OESK_WELabel_Default" style="z-index:2001">
                     <div class="OESZ OESZ_DivContent OESZG_WEe26293ffc4">
                      <span class="OESZ OESZ_Text OESZG_WEe26293ffc4 ContentBox">Customer Segments</span>
                     </div>
                    </div>
                   </div>
                  </div>
                 </div>
                </div>
                <div class="OERelLine OEHAlignC OEVAlignT">
                 <div id="WE8578612fd0" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WE8578612fd0">
                   <main id="Card5" draggable="true" ondragstart="drag(event)">
                    <div class="OECT OECT_Content OECTAbs OEDynTag0">
                     <div id="WEde38d0b6a8" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
                      <div class="OESZ OESZ_DivContent OESZG_WEde38d0b6a8">
                       <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                        <div id="WE619cc8ad9e" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                         <div class="OESZ OESZ_DivContent OESZG_WE619cc8ad9e">
                          <a href="javascript:alert('test');">
                           <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WE619cc8ad9e" alt="" />
                          </a>
                         </div>
                        </div>
                        <div id="WEc76c532efc" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                         <div class="OESZ OESZ_DivContent OESZG_WEc76c532efc">
                          <span class="OESZ OESZ_Text OESZG_WEc76c532efc ContentBox">Titulo Card Demo 1<br /></span>
                         </div>
                        </div>
                       </div>
                      </div>
                     </div>
                    </div>
                   </main>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </div>
           </div>
          </div><div id="WE0592da2ead" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2006">
           <div class="OESZ OESZ_DivContent OESZG_WE0592da2ead">
            <div class="OECT OECT_Content OECTAbs OEDynTag0">
             <div id="WE_CostStructure" class="BaseDiv RNone OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
              <div class="OESZ OESZ_DivContent OESZG_WE_CostStructure">
               <div class="OECT OECT_Content OECTRel OEDynTag0">
                <div class="OERelLine OEHAlignC OEVAlignB">
                 <div id="WE303dcd4f43" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OECenterRH" style="z-index:2003">
                  <div class="OESZ OESZ_DivContent OESZG_WE303dcd4f43">
                   <div class="OECT OECT_Content OECTAbs OEDynTag0">
                    <div id="WEed9a393b9a" class="BaseDiv RBoth OEWECadre OESK_WECadre_Default" style="z-index:2003">
                     <div class="OESZ OESZ_DivContent OESZG_WEed9a393b9a">
                      <div class="OESZ OESZ_Top OESZG_WEed9a393b9a"></div>
                      <div class="OESZ OESZ_Content OESZG_WEed9a393b9a"></div>
                      <div class="OESZ OESZ_Bottom OESZG_WEed9a393b9a"></div>
                     </div>
                    </div>
                    <div id="WEc7f49bfae9" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                     <div class="OESZ OESZ_DivContent OESZG_WEc7f49bfae9">
                      <img src="WEFiles/Image/WEImage/g3339-WEc7f49bfae9.png" class="OESZ OESZ_Img OESZG_WEc7f49bfae9" alt="" />
                     </div>
                    </div>
                    <div id="WE7b01a55b90" class="BaseDiv RWidth OEWELabel OESK_WELabel_Default" style="z-index:2001">
                     <div class="OESZ OESZ_DivContent OESZG_WE7b01a55b90">
                      <span class="OESZ OESZ_Text OESZG_WE7b01a55b90 ContentBox">Cost Structure</span>
                     </div>
                    </div>
                   </div>
                  </div>
                 </div>
                </div>
                <div class="OERelLine OEHAlignC OEVAlignT">
                 <div id="WE3276b6fc78" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WE3276b6fc78">
                   <main id="Card8" draggable="true" ondragstart="drag(event)">
                    <div class="OECT OECT_Content OECTAbs OEDynTag0">
                     <div id="WEcb9e91dbf7" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
                      <div class="OESZ OESZ_DivContent OESZG_WEcb9e91dbf7">
                       <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                        <div id="WE43709d07a3" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                         <div class="OESZ OESZ_DivContent OESZG_WE43709d07a3">
                          <a href="javascript:alert('test');">
                           <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WE43709d07a3" alt="" />
                          </a>
                         </div>
                        </div>
                        <div id="WE9e70740b9e" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                         <div class="OESZ OESZ_DivContent OESZG_WE9e70740b9e">
                          <span class="OESZ OESZ_Text OESZG_WE9e70740b9e ContentBox">Titulo Card Demo 1<br /></span>
                         </div>
                        </div>
                       </div>
                      </div>
                     </div>
                    </div>
                   </main>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </div>
           </div>
          </div><div id="WEc5f7dd1433" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2007">
           <div class="OESZ OESZ_DivContent OESZG_WEc5f7dd1433">
            <div class="OECT OECT_Content OECTAbs OEDynTag0">
             <div id="WE_RevenueStreams" class="BaseDiv RNone OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
              <div class="OESZ OESZ_DivContent OESZG_WE_RevenueStreams">
               <div class="OECT OECT_Content OECTRel OEDynTag0">
                <div class="OERelLine OEHAlignC OEVAlignB">
                 <div id="WE8fd9110707" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default OECenterRH" style="z-index:2002">
                  <div class="OESZ OESZ_DivContent OESZG_WE8fd9110707">
                   <div class="OECT OECT_Content OECTAbs OEDynTag0">
                    <div id="WE4f73478ff9" class="BaseDiv RBoth OEWECadre OESK_WECadre_Default" style="z-index:2003">
                     <div class="OESZ OESZ_DivContent OESZG_WE4f73478ff9">
                      <div class="OESZ OESZ_Top OESZG_WE4f73478ff9"></div>
                      <div class="OESZ OESZ_Content OESZG_WE4f73478ff9"></div>
                      <div class="OESZ OESZ_Bottom OESZG_WE4f73478ff9"></div>
                     </div>
                    </div>
                    <div id="WE59cb64135a" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                     <div class="OESZ OESZ_DivContent OESZG_WE59cb64135a">
                      <img src="WEFiles/Image/WEImage/g3311-WE59cb64135a.png" class="OESZ OESZ_Img OESZG_WE59cb64135a" alt="" />
                     </div>
                    </div>
                    <div id="WE32f1c6c765" class="BaseDiv RWidth OEWELabel OESK_WELabel_Default" style="z-index:2001">
                     <div class="OESZ OESZ_DivContent OESZG_WE32f1c6c765">
                      <span class="OESZ OESZ_Text OESZG_WE32f1c6c765 ContentBox">Revenue Streams</span>
                     </div>
                    </div>
                   </div>
                  </div>
                 </div>
                </div>
                <div class="OERelLine OEHAlignC OEVAlignT">
                 <div id="WEbd7da0d667" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
                  <div class="OESZ OESZ_DivContent OESZG_WEbd7da0d667">
                   <main id="Card9" draggable="true" ondragstart="drag(event)">
                    <div class="OECT OECT_Content OECTAbs OEDynTag0">
                     <div id="WE16a17a03f1" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">
                      <div class="OESZ OESZ_DivContent OESZG_WE16a17a03f1">
                       <div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">
                        <div id="WE08909abdc4" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">
                         <div class="OESZ OESZ_DivContent OESZG_WE08909abdc4">
                          <a href="javascript:alert('test');">
                           <img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WE08909abdc4" alt="" />
                          </a>
                         </div>
                        </div>
                        <div id="WE5f29e4e4e4" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">
                         <div class="OESZ OESZ_DivContent OESZG_WE5f29e4e4e4">
                          <span class="OESZ OESZ_Text OESZG_WE5f29e4e4e4 ContentBox">Titulo Card Demo 1<br /></span>
                         </div>
                        </div>
                       </div>
                      </div>
                     </div>
                    </div>
                   </main>
                  </div>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </div>
           </div>
          </div>
         </div>
        </div>
       </div>
      </div>
     </div>
    </div>
   </div>
  </div>
  <script type="text/javascript">
   const _KeyPartner = document.getElementById('WE_KeyPatner').children[0].children[0].children[1];
   const _KeyActivities = document.getElementById('WE_KeyActivities').children[0].children[0].children[1];
   const _ValueProposition = document.getElementById('WE_ValuePropositions').children[0].children[0].children[1];
   const _CustomerRelationchips = document.getElementById('WE_CustomerRelationship').children[0].children[0].children[1];
   const _CustomSegments = document.getElementById('WE_CustomersSegments').children[0].children[0].children[1];
   const _KeyResources = document.getElementById('WE_KeyResources').children[0].children[0].children[1];
   const _Channels = document.getElementById('WE_Channels').children[0].children[0].children[1];
   const _CostStructure = document.getElementById('WE_CostStructure').children[0].children[0].children[1];
   const _RevenueStreams = document.getElementById('WE_RevenueStreams').children[0].children[0].children[1];
   
   const _Libres = document.getElementById('WE0b12853407').children[0].children[0].children[1];
   
   Sprint = 6;
   
   const _Pos = [_Libres, _KeyPartner, _KeyActivities, _ValueProposition, _CustomerRelationchips, _CustomSegments, _KeyResources, _Channels, _CostStructure, _RevenueStreams];
   
   game_cards = [
   	{tipo: 1, id:'1', titulo:'Card Sprint1 N61', detalle:'detalle demo 61', tips:'tips demo 61', pos:'0', obj: ''},
   	{tipo: 1, id:'2', titulo:'Card Sprint1 N22', detalle:'detalle demo 22', tips:'tips demo 22', pos:'0', obj: ''},
   	{tipo: 1, id:'3', titulo:'Card Sprint1 N34', detalle:'detalle demo 34', tips:'tips demo 34', pos:'0', obj: ''},
   	{tipo: 1, id:'42', titulo:'Card Sprint1 N42', detalle:'detalle demo 42', tips:'tips demo 42', pos:'0', obj: ''},
   	{tipo: 1, id:'43', titulo:'Card Sprint1 N32', detalle:'detalle demo 32', tips:'tips demo 32', pos:'0', obj: ''},
   	{tipo: 1, id:'44', titulo:'Card Sprint1 N04', detalle:'detalle demo 04', tips:'tips demo 04', pos:'0', obj: ''},
   	{tipo: 1, id:'41', titulo:'Card Sprint1 N01', detalle:'detalle demo 01', tips:'tips demo 01', pos:'0', obj: ''},
   	
   	{tipo: 2, id:'4', titulo:'Card Sprint2 N04', detalle:'detalle demo 14', tips:'tips demo 14', pos:'0', obj: ''},
   	{tipo: 2, id:'5', titulo:'Card Sprint2 N15', detalle:'detalle demo 15', tips:'tips demo 15', pos:'0', obj: ''},
   	{tipo: 2, id:'6', titulo:'Card Sprint2 N26', detalle:'detalle demo 26', tips:'tips demo 27', pos:'0', obj: ''},
   	{tipo: 2, id:'7', titulo:'Card Sprint2 N27', detalle:'detalle demo 27', tips:'tips demo 80', pos:'0', obj: ''},
   	{tipo: 2, id:'8', titulo:'Card Sprint2 N80', detalle:'detalle demo 80', tips:'tips demo 80', pos:'0', obj: ''},
   	{tipo: 2, id:'9', titulo:'Card Sprint2 N19', detalle:'detalle demo 19', tips:'tips demo 19', pos:'0', obj: ''},
   	{tipo: 2, id:'10', titulo:'Card Sprint2 N26', detalle:'detalle demo 26', tips:'tips demo 26', pos:'0', obj: ''},
   	
   	{tipo: 3, id:'11', titulo:'Card Sprint3 N27', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 3, id:'12', titulo:'Card Sprint3 N71', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 3, id:'13', titulo:'Card Sprint3 N12', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 3, id:'14', titulo:'Card Sprint3 N27', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 3, id:'15', titulo:'Card Sprint3 N71', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 3, id:'16', titulo:'Card Sprint3 N12', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 3, id:'17', titulo:'Card Sprint3 N12', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	
   	{tipo: 4, id:'18', titulo:'Card Sprint4 N15', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 4, id:'19', titulo:'Card Sprint4 N63', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 4, id:'20', titulo:'Card Sprint4 N44', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 4, id:'21', titulo:'Card Sprint4 N15', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 4, id:'22', titulo:'Card Sprint4 N63', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 4, id:'23', titulo:'Card Sprint4 N44', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 4, id:'24', titulo:'Card Sprint4 N44', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	
   	{tipo: 5, id:'25', titulo:'Card Sprint5 N19', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 5, id:'26', titulo:'Card Sprint5 N75', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 5, id:'27', titulo:'Card Sprint5 N14', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 5, id:'28', titulo:'Card Sprint5 N19', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 5, id:'29', titulo:'Card Sprint5 N75', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 5, id:'30', titulo:'Card Sprint5 N14', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	
   	{tipo: 6, id:'31', titulo:'Card Sprint6 N32', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 6, id:'32', titulo:'Card Sprint6 N16', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 6, id:'33', titulo:'Card Sprint6 N09', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 6, id:'34', titulo:'Card Sprint6 N05', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 6, id:'35', titulo:'Card Sprint6 N32', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 6, id:'36', titulo:'Card Sprint6 N16', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 6, id:'37', titulo:'Card Sprint6 N09', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 6, id:'38', titulo:'Card Sprint6 N05', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 6, id:'39', titulo:'Card Sprint6 N09', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	{tipo: 6, id:'40', titulo:'Card Sprint6 N05', detalle:'detalle demo 1', tips:'tips demo 1', pos:'0', obj: ''},
   	
   	];
   
   Limpieza = () => {
   	for (i=0; i < _Pos.length ;i++){
   		_Pos[i].innerHTML = "";
   	}
   }
   
   /// Emparentar Objetos:
   for (a=0; a < game_cards.length; a++){
   	game_cards[a].obj = CrearItemCards(game_cards[a].tipo, game_cards[a].id, game_cards[a].titulo, a)
   }
   
   ColocarCards = () => {
   	for (a=0; a < game_cards.length; a++){
   		if (game_cards[a].tipo <= Sprint){
   			_Pos[game_cards[a].pos].appendChild(game_cards[a].obj);
   		}
   	}
   }
   
   
   Limpieza();
   ColocarCards();
   
   
   function CrearItemCards (tipo, id, titulo, i) {
   	
   	switch (tipo){
   		case 1:
   			Printer = '<div id="WE_CARD_demo1" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2002">'+
              '<div class="OESZ OESZ_DivContent OESZG_WE_CARD_demo1">'+
               '<main id="'+id+'" draggable="true" ondragstart="drag(event)">'+
                '<div class="OECT OECT_Content OECTAbs OEDynTag0">'+
                 '<div id="WE600431a48a" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">'+
                  '<div class="OESZ OESZ_DivContent OESZG_WE600431a48a">'+
                   '<div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">'+
                    '<div id="WE3871e97495" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">'+
                     '<div class="OESZ OESZ_DivContent OESZG_WE3871e97495">'+
                      '<a href="javascript:MostrarTarjeta(true, '+i+');">'+
                       '<img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WE3871e97495" alt="" />'+
                      '</a>'+
                     '</div>'+
                    '</div>'+
                    '<div id="WE854a4c6608" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">'+
                     '<div class="OESZ OESZ_DivContent OESZG_WE854a4c6608">'+
                      '<span class="OESZ OESZ_Text OESZG_WE854a4c6608 ContentBox">'+titulo+'<br /></span>'+
                     '</div>'+
                    '</div>'+
                   '</div>'+
                  '</div>'+
                 '</div>'+
                '</div>'+
               '</main>'+
              '</div>'+
             '</div>';
   		break;
   		case 2:
   			Printer = '<div id="WEa19b3e9496" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2002">'+
              '<div class="OESZ OESZ_DivContent OESZG_WEa19b3e9496">'+
               '<main id="'+id+'" draggable="true" ondragstart="drag(event)">'+
                '<div class="OECT OECT_Content OECTAbs OEDynTag0">'+
                 '<div id="WE9aa95f04f1" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">'+
                  '<div class="OESZ OESZ_DivContent OESZG_WE9aa95f04f1">'+
                   '<div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">'+
                    '<div id="WEc26b1fa455" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">'+
                     '<div class="OESZ OESZ_DivContent OESZG_WEc26b1fa455">'+
                      '<a href="javascript:MostrarTarjeta(true, '+i+');">'+
                       '<img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WEc26b1fa455" alt="" />'+
                      '</a>'+
                     '</div>'+
                    '</div>'+
                    '<div id="WEcc4275897f" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">'+
                     '<div class="OESZ OESZ_DivContent OESZG_WEcc4275897f">'+
                      '<span class="OESZ OESZ_Text OESZG_WEcc4275897f ContentBox">'+titulo+'<br /></span>'+
                     '</div>'+
                    '</div>'+
                   '</div>'+
                  '</div>'+
                 '</div>'+
                '</div>'+
              '</main>'+
              '</div>'+
             '</div>';
   		break;
   		case 3:
   			Printer = '<div id="WE980fb9c2a5" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2003">'+
              '<div class="OESZ OESZ_DivContent OESZG_WE980fb9c2a5">'+
               '<main id="'+id+'" draggable="true" ondragstart="drag(event)">'+
                '<div class="OECT OECT_Content OECTAbs OEDynTag0">'+
                 '<div id="WE07f7cf90a4" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">'+
                  '<div class="OESZ OESZ_DivContent OESZG_WE07f7cf90a4">'+
                   '<div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">'+
                    '<div id="WEa9fb890e09" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">'+
                     '<div class="OESZ OESZ_DivContent OESZG_WEa9fb890e09">'+
                      '<a href="javascript:MostrarTarjeta(true, '+i+');">'+
                       '<img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WEa9fb890e09" alt="" />'+
                      '</a>'+
                     '</div>'+
                    '</div>'+
                    '<div id="WE649f838144" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">'+
                     '<div class="OESZ OESZ_DivContent OESZG_WE649f838144">'+
                      '<span class="OESZ OESZ_Text OESZG_WE649f838144 ContentBox">'+titulo+'<br /></span>'+
                     '</div>'+
                    '</div>'+
                   '</div>'+
                  '</div>'+
                 '</div>'+
                '</div>'+
               '</main>'+
              '</div>'+
             '</div>';
   		break;
   		case 4:
   			Printer = '<div id="WEbb996faad8" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2004">'+
              '<div class="OESZ OESZ_DivContent OESZG_WEbb996faad8">'+
               '<main id="'+id+'" draggable="true" ondragstart="drag(event)">'+
                '<div class="OECT OECT_Content OECTAbs OEDynTag0">'+
                 '<div id="WE86f89c7d60" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">'+
                  '<div class="OESZ OESZ_DivContent OESZG_WE86f89c7d60">'+
                   '<div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">'+
                    '<div id="WE0fddb928b4" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">'+
                     '<div class="OESZ OESZ_DivContent OESZG_WE0fddb928b4">'+
                      '<a href="javascript:MostrarTarjeta(true, '+i+');">'+
                       '<img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WE0fddb928b4" alt="" />'+
                      '</a>'+
                     '</div>'+
                    '</div>'+
                    '<div id="WEe29ccd68c0" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">'+
                     '<div class="OESZ OESZ_DivContent OESZG_WEe29ccd68c0">'+
                      '<span class="OESZ OESZ_Text OESZG_WEe29ccd68c0 ContentBox">'+titulo+'<br /></span>'+
                     '</div>'+
                    '</div>'+
                   '</div>'+
                  '</div>'+
                '</div>'+
                '</div>'+
               '</main>'+
              '</div>'+
             '</div>';
   		break;
   		case 5:
   			Printer = '<div id="WE3cc132a49c" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2005">'+
              '<div class="OESZ OESZ_DivContent OESZG_WE3cc132a49c">'+
               '<main id="'+id+'" draggable="true" ondragstart="drag(event)">'+
                '<div class="OECT OECT_Content OECTAbs OEDynTag0">'+
                 '<div id="WE224587bd4f" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">'+
                  '<div class="OESZ OESZ_DivContent OESZG_WE224587bd4f">'+
                   '<div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">'+
                    '<div id="WE06ce20920f" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">'+
                     '<div class="OESZ OESZ_DivContent OESZG_WE06ce20920f">'+
                      '<a href="javascript:MostrarTarjeta(true, '+i+');">'+
                       '<img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WE06ce20920f" alt="" />'+
                      '</a>'+
                     '</div>'+
                    '</div>'+
                    '<div id="WE2499bc0bc5" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">'+
                     '<div class="OESZ OESZ_DivContent OESZG_WE2499bc0bc5">'+
                      '<span class="OESZ OESZ_Text OESZG_WE2499bc0bc5 ContentBox">'+titulo+'<br /></span>'+
                     '</div>'+
                    '</div>'+
                   '</div>'+
                  '</div>'+
                 '</div>'+
                '</div>'+
               '</main>'+
              '</div>'+
             '</div>';
   		break;
   		case 6:
   			Printer = '<div id="WE6c7b021071" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2006">'+
              '<div class="OESZ OESZ_DivContent OESZG_WE6c7b021071">'+
               '<main id="'+id+'" draggable="true" ondragstart="drag(event)">'+
                '<div class="OECT OECT_Content OECTAbs OEDynTag0">'+
                 '<div id="WE9249cbbf4d" class="BaseDiv RBoth OEWEPanel OESK_WEPanel_Default" style="z-index:2001">'+
                  '<div class="OESZ OESZ_DivContent OESZG_WE9249cbbf4d">'+
                   '<div class="OECT OECT_Content OECTAbs OEDynTag0" style="overflow:hidden">'+
                    '<div id="WE77736ab900" class="BaseDiv RKeepRatio OEWEImage OESK_WEImage_Default" style="z-index:2002">'+
                     '<div class="OESZ OESZ_DivContent OESZG_WE77736ab900">'+
                      '<a href="javascript:MostrarTarjeta(true, '+i+');">'+
                       '<img src="WEFiles/Image/WEImage/view_card-WE3871e97495.png" class="OESZ OESZ_Img OESZG_WE77736ab900" alt="" />'+
                      '</a>'+
                     '</div>'+
                    '</div>'+
                    '<div id="WE5aaa7f08f5" class="BaseDiv RNone OEWELabel OESK_WELabel_Default" style="z-index:2001">'+
                     '<div class="OESZ OESZ_DivContent OESZG_WE5aaa7f08f5">'+
                      '<span class="OESZ OESZ_Text OESZG_WE5aaa7f08f5 ContentBox">'+titulo+'<br /></span>'+
                     '</div>'+
                    '</div>'+
                   '</div>'+
                  '</div>'+
                 '</div>'+
                '</div>'+
               '</main>'+
              '</div>'+
             '</div>';
   		break;
   		
   	}
   	
   	var obj = document.createElement('div');
   	obj.innerHTML = Printer;
   	
   	return obj.firstChild
   	
   }
   
   
   // Drag&Drop:
   
   allowDrop = (ev) => {
     ev.preventDefault();
   	if (ev.target.id != ""){
   		ev.target.setAttribute("style", "background:#eaeaea")
   		} else {
   			check = ev.target.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement
   				.parentElement.parentElement
   			
   			if (check.id == "WE_KeyPatner"
   		|| check.id == "WE_KeyActivities"
   		|| check.id == "WE_ValuePropositions"
   		|| check.id == "WE_CustomerRelationship"
   		|| check.id == "WE_CustomersSegments"
   		|| check.id == "WE_KeyResources"
   		|| check.id == "WE_Channels"
   		|| check.id =="WE_CostStructure"
   		|| check.id == "WE_RevenueStreams"){
   				check.setAttribute("style", "background:#eaeaea")
   			}
   		}
   	
   }
   
   leaveDrop = (ev) => {
   	ev.preventDefault();
   	ev.target.setAttribute("style", "")
   }
   
   drag = (ev) => {
     ev.dataTransfer.setData("text", ev.target.id);
     //ev.dataTransfer.setData('text/plain', e.target.id);
   }
   
   drop = (ev) => {
     ev.preventDefault();
   	ev.target.setAttribute("style", "")
     var data = ev.dataTransfer.getData("text");
   	//console.log(ev.target.children[0].children[0].children[1]);
   	//console.log(document.getElementById(data).parentElement.parentElement);
   	if (ev.target.id == "WE_KeyPatner"
   		|| ev.target.id == "WE_KeyActivities"
   		|| ev.target.id == "WE_ValuePropositions"
   		|| ev.target.id == "WE_CustomerRelationship"
   		|| ev.target.id == "WE_CustomersSegments"
   		|| ev.target.id == "WE_KeyResources"
   		|| ev.target.id == "WE_Channels"
   		|| ev.target.id =="WE_CostStructure"
   		|| ev.target.id == "WE_RevenueStreams"){
   	
   	ev.target
   		.children[0]
   		.children[0]
   		.children[1]
   		.appendChild(document.getElementById(data).parentElement.parentElement);
   		
   	}
   	
   	check = ev.target.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement
   				.parentElement.parentElement
   			
   			if (check.id == "WE_KeyPatner"
   		|| check.id == "WE_KeyActivities"
   		|| check.id == "WE_ValuePropositions"
   		|| check.id == "WE_CustomerRelationship"
   		|| check.id == "WE_CustomersSegments"
   		|| check.id == "WE_KeyResources"
   		|| check.id == "WE_Channels"
   		|| check.id =="WE_CostStructure"
   		|| check.id == "WE_RevenueStreams"){
   				
   				check
   				.children[0]
   				.children[0]
   				.children[1]
   				.appendChild(document.getElementById(data).parentElement.parentElement)
   			}
   	
   	console.log(ev.target
   				.parentElement
   				.parentElement
   				.parentElement
   				.parentElement
   				.parentElement
   				.parentElement
   				.parentElement
   				.parentElement
   				.parentElement
   				.parentElement
   				.id); // ObtengoDestino
   	
     //ev.target.appendChild(document.getElementById(data));
   }
   
   ;
   const DragablesPanels = ["WE0b12853407","WE_KeyPatner", "WE_KeyActivities", "WE_KeyResources", "WE_ValuePropositions", "WE_CustomerRelationship", "WE_Channels", "WE_CostStructure",
   "WE_RevenueStreams", "WE_CustomersSegments",]
   
   
   for (p=0; p < DragablesPanels.length; p++){
   	document.getElementById(DragablesPanels[p]).setAttribute("ondrop", "drop(event)");	
   	document.getElementById(DragablesPanels[p]).setAttribute("ondragover", "allowDrop(event)");
   	document.getElementById(DragablesPanels[p]).setAttribute("ondragleave", "leaveDrop(event)");
   }
   
   var Tarjetas = document.getElementById("WEcb32818414");
   
   /*var preloadLink = document.createElement("link");
   preloadLink.href = "myscript.js";
   preloadLink.rel = "preload";
   preloadLink.as = "script";
   document.head.appendChild(preloadLink);
   */
  </script><?php
  $Partidas = file_get_contents('partida.htm');
$Dashboard = file_get_contents('Dashboard.htm');
//$fix = str_replace('"', '\"', $test);
/*$fixPartidas = str_replace("'", "\'", $Partidas);
$fixPartidas = str_replace(PHP_EOL, '', $fixPartidas);
$fixPartidas = str_replace("</script>", "<\/script>", $fixPartidas);*/

function FixHTML($s){
	$fix = str_replace("'", "\'", $s);
	$fix = str_replace(PHP_EOL, '', $fix);
	$fix = str_replace("</script>", "<\/script>", $fix);
	return $fix;
}


echo "	<script type='text/javascript'>
var pantallapartida='".FixHTML($Partidas)."';
var PantallDashboard='".FixHTML($Dashboard)."';



var pp = document.createElement('html');
pp.innerHTML = pantallapartida;
document.head.appendChild(pp.children[0].cloneNode(true));

var pd = document.createElement('html');
pd.innerHTML = PantallDashboard;
document.head.appendChild(pd.children[0].cloneNode(true));

const _PP = pp.children[1].cloneNode(true);
const _PD = pd.children[1].cloneNode(true);
const _CMB = document.body.cloneNode(true);

function CambiarPartida(){
	document.body = _PP;
	OE.CssEvents.initialize()
}

function CambiarDash(){
	document.body = _PD;
	OE.CssEvents.initialize()
}

function CambiarCanvas(){
	document.body = _CMB;
	OE.CssEvents.initialize()
}

</script>";


  ?>

 </body>
</html>